import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-10 bg-green-300 p-5 justify-center">
          <Link href="./" className="hover:text-white">Home</Link>
          <Link href="/namePage"className="hover:text-white">NamePage</Link>
          <Link href="/services"className="hover:text-white">Services</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
