import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import dashBorad from "./dashBoard/page";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}:Readonly<{children:React.ReactNode}>){
  return(
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-gray-400 p-5 flex gap-10">
        <Link href='/'> Home</Link>
        <Link href='/dashBoard'> dashboard</Link>
        <Link href='/aboutUs'> About Us</Link>
        <Link href='/blog'> blog</Link>
        <Link href='/settings'> settings</Link>
        <Link href='/settings/settings1'> settings1</Link>
        <Link href='/settings/settings2'> settings2</Link>
      </header>
        {children}
      <div className="bg-gray-400 p-20 mt-20">
        This is footer
        <Link href = '/blog/blog1'>Blog1</Link>
      </div>
      </body>
    </html>
  )
}
